version: '3.8'

services:
  db:
    image: postgres:16.1
    env_file: ../.env
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/

  backend:
    build: ../backend/
    env_file: ../.env
    restart: always
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/
      - ../data/ingredients.csv:/app/data/ingredients.csv
      - ../data/tags.csv:/app/data/tags.csv

  frontend:
    build: ../frontend/
    env_file: ../.env
    depends_on:
      - backend
    volumes:
      - frontend_data:/app/build/

  nginx:
    image: nginx:1.25.3
    ports:
      - 80:80
    restart: always
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
      - frontend_data:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

volumes:
  db_data:
  static:
  media:
  frontend_data:
